server:
  port: 8080

spring:
  application:
    name: techblog
  jpa:
    hibernate:
      ddl-auto: create
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET_KEY}
